import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

export default defineConfig({
  plugins: [react()],
  resolve: { alias: { '@': path.resolve(__dirname, 'src') } },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/unit/**/*.test.{ts,tsx}'],
    // Mock out the PWA virtual module so tests that import main.tsx
    // (or anything that pulls in the service-worker bootstrap) don't
    // crash. The module is generated by vite-plugin-pwa at build time
    // only and never resolves under vitest.
    alias: {
      'virtual:pwa-register': path.resolve(__dirname, 'tests/__mocks__/pwa-register.ts'),
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html', 'lcov'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        // Test files themselves
        'src/**/*.test.{ts,tsx}',
        // Entry / wiring — exercised at runtime, not in unit tests
        'src/main.tsx',
        // MSW mocks are dev-only, not part of the runtime app
        'src/mocks/**',
        // Type-only / ambient declarations carry no runtime code
        'src/vite-env.d.ts',
        // Pure type re-exports (DTOs, shared interfaces)
        'src/lib/api/types.ts',
        // shadcn-style UI primitives are presentational and tested
        // through their consuming pages / e2e. Including them skews
        // the metric against the logic we actually own.
        'src/components/ui/**',
        // Page components are exercised by Playwright e2e; unit
        // testing every page would duplicate effort. Each page is
        // still type-checked and lint-checked.
        'src/app/**',
      ],
      // Gates applied by `pnpm test:coverage`. Lines / statements / branches
      // are the primary quality signal; functions is set lower because
      // exported wrappers (e.g. apiClient.get/post/put/delete are counted
      // as four functions even though they're one-liners) inflate the
      // denominator without adding real coverage work.
      thresholds: {
        lines: 70,
        functions: 60,
        branches: 60,
        statements: 70,
      },
    },
  },
});