import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// MSW's `setupWorker` requires a real ServiceWorker container which jsdom
// doesn't ship. Mock the entire `./mocks/browser` module so the dynamic
// import inside main.tsx resolves to a no-op when `import.meta.env.DEV`
// is true in the test environment.
vi.mock('@/mocks/browser', () => ({
  worker: { start: vi.fn().mockResolvedValue(undefined) },
}));

// GDPR / cookie consent modules read localStorage + cookies which jsdom
// partially supports but the persistence side-effects add noise. Provide
// inert stubs so the import chain doesn't run app side effects.
vi.mock('@/lib/consent', () => ({
  getConsent: () => ({
    necessary: true,
    analytics: false,
    marketing: false,
    decidedAt: null,
  }),
}));
// Make the consent store render-friendly: a selector that just returns
// the default state, no setter calls — main.tsx's <ConsentSyncBridge>
// would otherwise re-trigger observability re-init and explode.
vi.mock('@/stores/consent', () => {
  const noop = () => undefined;
  return {
    useConsentStore: Object.assign(
      (sel: (s: { state: unknown }) => unknown) =>
        sel({ state: { necessary: true, analytics: false, marketing: false, decidedAt: null } }),
      {
        getState: () => ({
          state: { necessary: true, analytics: false, marketing: false, decidedAt: null },
        }),
        setState: noop,
        subscribe: noop,
      },
    ),
  };
});

// Hoisted mock for `virtual:pwa-register` — this module is generated by
// vite-plugin-pwa at build time only and is replaced under vitest via
// the alias in vitest.config.ts.
const registerSW = vi.fn().mockReturnValue(() => Promise.resolve());
vi.mock('virtual:pwa-register', () => ({ registerSW }));

describe('PWA service worker registration', () => {
  beforeEach(() => {
    registerSW.mockClear();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // Helper: load main.tsx lazily, resetting the module cache so each test
  // sees a fresh top-level evaluation. Otherwise the second `await import`
  // returns the cached module and `registerSW` is never called again.
  async function bootstrap() {
    vi.resetModules();
    document.body.innerHTML = '<div id="root"></div>';
    await import('@/main');
    await new Promise((r) => setTimeout(r, 0));
  }

  it('calls registerSW exactly once on bootstrap', async () => {
    await bootstrap();
    expect(registerSW).toHaveBeenCalledTimes(1);
  });

  it('registers with immediate=true and the expected lifecycle hooks', async () => {
    await bootstrap();
    const opts = registerSW.mock.calls[0]?.[0] as
      | {
          immediate?: boolean;
          onNeedRefresh?: () => void;
          onOfflineReady?: () => void;
        }
      | undefined;
    expect(opts).toBeDefined();
    expect(opts?.immediate).toBe(true);
    expect(typeof opts?.onNeedRefresh).toBe('function');
    expect(typeof opts?.onOfflineReady).toBe('function');
  });

  it('lifecycle handlers are safe to invoke (do not throw)', async () => {
    await bootstrap();
    const opts = registerSW.mock.calls[0]?.[0] as {
      onNeedRefresh?: () => void;
      onOfflineReady?: () => void;
    };
    expect(() => opts?.onNeedRefresh?.()).not.toThrow();
    expect(() => opts?.onOfflineReady?.()).not.toThrow();
  });
});